apiVersion: v1
kind: Service
metadata:
  name: server-grpc-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: server-grpc
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
