apiVersion: v1
kind: Service
metadata:
  name: discovery-server-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: discovery-server
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9010
      nodePort: {{ .Values.service.nodePort }}
