replicaCount: 1

image:
  repository: riccardo170697/discovery-server
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9010
  nodePort: 30010

serviceAccount:
  name: discovery-sa

tlsSecretName: tls-cert-secret
