apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-manager
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-manager
  template:
    metadata:
      labels:
        app: node-manager
    spec:
      serviceAccountName: node-manager
      containers:
      - name: node-manager
        image: node-manager:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9009
        volumeMounts:
        - name: tls-cert
          mountPath: /app/certificates
          readOnly: true
      volumes:
      - name: tls-cert
        secret:
          secretName: tls-cert-secret
---
apiVersion: v1
kind: Service
metadata:
  name: node-manager-svc
  namespace: demo
spec:
  selector:
    app: node-manager
  ports:
    - protocol: TCP
      port: 9009
      targetPort: 9009
      nodePort: 30009
  type: NodePort