replicaCount: 1

image:
  repository: riccardo170697/node-manager
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9009
  nodePort: 30009

serviceAccount:
  name: node-manager

tlsSecretName: tls-cert-secret
