apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-manager
  template:
    metadata:
      labels:
        app: node-manager
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: node-manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: tls-cert
              mountPath: /app/certificates
              readOnly: true
      volumes:
        - name: tls-cert
          secret:
            secretName: {{ .Values.tlsSecretName }}
