apiVersion: v1
kind: Service
metadata:
  name: node-manager-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: node-manager
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
